grafana:
  grafana.ini:
    server:
      root_url: "http://20.235.48.180/grafana/"
      serve_from_sub_path: true
  persistence:
    enabled: true
    type: pvc
    storageClassName: local-path
    size: 1Gi
