apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: azureops-copilot-tls
  namespace: azureops-copilot
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`devopspk.online`) || Host(`www.devopspk.online`)
    kind: Rule
    priority: 1
    services:
    - name: waf-proxy
      port: 80
  tls:
    certResolver: letsencrypt
    domains:
    - main: devopspk.online
      sans:
      - www.devopspk.online
